# Generated by Django 6.0.7 on 2026-07-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_categoria_options_remove_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA/'),
        ),
    ]
